### ISSUE TITLE
Move this line up

### ISSUE THREAD

**Issue by tpoisot** [MichielStock/Just_for_fun#5]
This line:

https://github.com/MichielStock/Just_for_fun/blob/189e0d050dd94f0fdf9c8a3d50da02235bf99c3f/StatisticalPhysics/statisticalphysics.jl#L41

can be in the loop just before. It will be run `n` times instead than `n*(n-1)` times.

**Comment by MichielStock** [comment]
Yes, though the big win here would be to find some data structure or algorithm to check if the circles are overlapping in smaller than quadratic time.
